import { createHash } from "node:crypto";
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==="object"?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
export const digest=v=>`sha256:${createHash("sha256").update(JSON.stringify(canonical(v))).digest("hex")}`;
const verdict=(result,reason,evidence)=>({result,reason,evidence});
const topic=(config,id)=>config.topics.find(item=>item.id===id);
export function plan(config,operation){const subject=topic(config,operation.topicId);if(!subject||subject.connectorId!==operation.connectorId||!operation.expectedRevision||!operation.configuration)return verdict("fail","policy_failure");if(!config.authority.mutate)return verdict("fail","authorization_failure");const exact={providerId:"confluent",clusterId:config.clusterId,topicId:operation.topicId,connectorId:operation.connectorId,expectedRevision:operation.expectedRevision,configuration:operation.configuration,operationId:operation.operationId};return{result:"pass",plan:exact,planDigest:digest(exact)};}
export function observe(config,response,now){if(!config.authority.consume)return verdict("fail","authorization_failure");if(response.error)return failure(response.error);if(response.clusterId!==config.clusterId||response.cloud!==config.cloud||response.region!==config.region||response.tier!==config.tier)return verdict("fail","selection_failure");if(config.complianceArtifacts.some(a=>a.tier!==config.tier||a.cloud!==config.cloud||a.region!==config.region))return verdict("fail","compliance_scope_failure");const subject=topic(config,response.topicId);if(!subject)return verdict("fail","policy_failure");if(response.schemaId!==subject.schemaId||response.schemaVersion!==subject.schemaVersion)return verdict("fail","schema_incompatible");const freshnessMs=Date.parse(now)-Date.parse(response.consumedAt),auditAgeMs=Date.parse(now)-Date.parse(response.auditObservedAt);if(!response.auditEventId||!Number.isFinite(auditAgeMs)||auditAgeMs>response.auditMaxAgeMs)return verdict("indeterminate","stale_audit_evidence");if(response.duplicate||response.replayed)return verdict("fail","duplicate_event");if(response.consumerLag>config.maxLag)return verdict("fail","consumer_lag_exceeded");if(response.cost>config.costLimit)return verdict("fail","cost_guardrail_exceeded");if(!response.destinationObserved)return verdict("indeterminate","end_outcome_unobserved");return verdict("pass","delivered",{providerId:"confluent",clusterId:config.clusterId,cloud:config.cloud,region:config.region,tier:config.tier,topicId:response.topicId,connectorId:subject.connectorId,schemaId:subject.schemaId,schemaVersion:subject.schemaVersion,correlationId:response.correlationId,payloadDigest:response.payloadDigest,partition:response.partition,offset:response.offset,producerAuthorityDigest:config.authority.producerDigest,consumerAuthorityDigest:config.authority.consumerDigest,produceAt:response.produceAt,consumedAt:response.consumedAt,freshnessMs,consumerLag:response.consumerLag,auditEventId:response.auditEventId,auditAuthorized:response.auditAuthorized,cost:response.cost,complianceArtifacts:config.complianceArtifacts});}
export function invoke(config,event,ack){if(!config.authority.produce)return verdict("fail","authorization_failure");const subject=topic(config,event.topicId);if(!subject||event.schemaId!==subject.schemaId||event.schemaVersion!==subject.schemaVersion)return verdict("fail","schema_incompatible");if(!event.correlationId||!event.idempotencyKey)return verdict("fail","event_identity_required");if(ack.error)return failure(ack.error);return verdict("pass","accepted",{correlationId:event.correlationId,payloadDigest:digest(event.payload),requestId:ack.requestId});}
export function apply(config,approved,write,readback,now){if(!approved?.plan||approved.approval?.planDigest!==digest(approved.plan))return verdict("fail","exact_approval_required");const proposed=plan(config,approved.plan);if(proposed.result!=="pass")return proposed;if(write.error)return failure(write.error);if(write.previousRevision!==approved.plan.expectedRevision)return verdict("fail","configuration_conflict");const observed=observe(config,readback,now);if(observed.result!=="pass")return observed;if(readback.configurationDigest!==digest(approved.plan.configuration))return verdict("fail","read_after_write_mismatch",observed.evidence);return verdict("pass","converged",{...observed.evidence,operationId:approved.plan.operationId,planDigest:approved.approval.planDigest,approvalId:approved.approval.id,readAfterWriteResult:"matched"});}
export function correlate(items){const ids=items.map(i=>`${i.clusterId}:${i.topicId}:${i.correlationId}:${i.payloadDigest}`);return ids.every(id=>id===ids[0])?verdict("pass","projections_agree"):verdict("fail","multimodal_evidence_mismatch");}
export function normalizeConnector(providerId,event){return{providerId,resourceId:event.resourceId,correlationId:event.correlationId,payloadDigest:event.payloadDigest,status:event.status,observedAt:event.observedAt};}
function failure(error){if(["invalid_api_key","rbac_denied"].includes(error))return verdict("fail","authorization_failure");if(["destination_unavailable","connector_failed","rate_limited","quota_exceeded"].includes(error))return verdict("indeterminate","provider_unavailable");return verdict("indeterminate","provider_error");}
